import type { Theme } from '../../types/theme';

export const dracula: Theme = {
  id: 'dracula',
  name: 'Dracula',
  author: 'Zeno Rocha',
  isPreset: true,
  isReadOnly: true,
  colors: {
    bg: {
      base: '#282a36',
      elevated: '#44475a',
      overlay: '#6272a4',
      input: '#282a36',
      tooltip: '#44475a',
    },
    surface: {
      primary: '#44475a',
      secondary: '#6272a4',
      tertiary: '#6c7290',
      hover: '#6272a4',
      active: '#bd93f9',
      disabled: '#44475a',
    },
    text: {
      primary: '#f8f8f2',
      secondary: '#6272a4',
      muted: '#6272a4',
      disabled: '#6c7290',
      accent: '#bd93f9',
      inverse: '#282a36',
    },
    accent: {
      primary: '#bd93f9',
      secondary: '#ff79c6',
      success: '#50fa7b',
      warning: '#f1fa8c',
      error: '#ff5555',
      info: '#8be9fd',
    },
    border: {
      subtle: '#44475a',
      default: '#6272a4',
      strong: '#6c7290',
      focus: '#bd93f9',
    },
    semantic: {
      string: '#f1fa8c',
      number: '#bd93f9',
      boolean: '#ff79c6',
      date: '#50fa7b',
      null: '#6272a4',
      primaryKey: '#ffb86c',
      foreignKey: '#8be9fd',
      index: '#ff79c6',
      connectionActive: '#50fa7b',
      connectionInactive: '#6272a4',
      modified: '#bd93f9',
      deleted: '#ff5555',
      new: '#50fa7b',
    },
  },
  typography: {
    fontFamily: {
      base: 'Inter, system-ui, sans-serif',
      mono: 'Fira Code, Monaco, Consolas, monospace',
    },
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
    },
  },
  layout: {
    borderRadius: {
      sm: '0.25rem',
      base: '0.5rem',
      lg: '0.75rem',
      xl: '1rem',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      base: '1rem',
      lg: '1.5rem',
      xl: '2rem',
    },
  },
  monacoTheme: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '6272A4' },
      { token: 'keyword', foreground: 'FF79C6' },
      { token: 'string', foreground: 'F1FA8C' },
      { token: 'number', foreground: 'BD93F9' },
      { token: 'regexp', foreground: 'F1FA8C' },
      { token: 'operator', foreground: 'FF79C6' },
      { token: 'namespace', foreground: 'F8F8F2' },
      { token: 'type', foreground: '8BE9FD' },
      { token: 'struct', foreground: '8BE9FD' },
      { token: 'class', foreground: '8BE9FD' },
      { token: 'interface', foreground: '8BE9FD' },
      { token: 'enum', foreground: '8BE9FD' },
      { token: 'typeParameter', foreground: '8BE9FD' },
      { token: 'function', foreground: '50FA7B' },
      { token: 'member', foreground: '50FA7B' },
      { token: 'macro', foreground: '50FA7B' },
      { token: 'variable', foreground: 'F8F8F2' },
      { token: 'parameter', foreground: 'FFB86C' },
      { token: 'property', foreground: 'F8F8F2' },
      { token: 'label', foreground: 'FF79C6' },
    ],
    colors: {
      'editor.background': '#282A36',
      'editor.foreground': '#F8F8F2',
      'editorLineNumber.foreground': '#6272A4',
      'editorLineNumber.activeForeground': '#F8F8F2',
      'editor.selectionBackground': '#44475A',
      'editor.selectionHighlightBackground': '#44475A',
      'editor.wordHighlightBackground': '#44475A',
      'editor.wordHighlightStrongBackground': '#44475A',
      'editor.findMatchBackground': '#6272A4',
      'editor.findMatchHighlightBackground': '#6272A4',
      'editor.findRangeHighlightBackground': '#44475A',
      'editor.hoverHighlightBackground': '#44475A',
      'editorCursor.foreground': '#F8F8F2',
      'editorIndentGuide.background': '#44475A',
      'editorIndentGuide.activeBackground': '#6272A4',
      'editorLineHighlightBackground': '#44475A',
      'editorLink.activeForeground': '#8BE9FD',
    },
  },
};
