import type { Theme } from '../../types/theme';

export const githubDark: Theme = {
  id: 'github-dark',
  name: 'GitHub Dark',
  author: 'GitHub',
  isPreset: true,
  isReadOnly: true,
  colors: {
    bg: {
      base: '#0d1117',
      elevated: '#161b22',
      overlay: '#21262d',
      input: '#0d1117',
      tooltip: '#161b22',
    },
    surface: {
      primary: '#161b22',
      secondary: '#21262d',
      tertiary: '#30363d',
      hover: '#21262d',
      active: '#58a6ff',
      disabled: '#161b22',
    },
    text: {
      primary: '#c9d1d9',
      secondary: '#8b949e',
      muted: '#6e7681',
      disabled: '#484f58',
      accent: '#58a6ff',
      inverse: '#0d1117',
    },
    accent: {
      primary: '#58a6ff',
      secondary: '#a371f7',
      success: '#3fb950',
      warning: '#d29922',
      error: '#f85149',
      info: '#79c0ff',
    },
    border: {
      subtle: '#161b22',
      default: '#30363d',
      strong: '#484f58',
      focus: '#58a6ff',
    },
    semantic: {
      string: '#a5d6ff',
      number: '#79c0ff',
      boolean: '#ff7b72',
      date: '#7ee787',
      null: '#6e7681',
      primaryKey: '#d29922',
      foreignKey: '#79c0ff',
      index: '#ff7b72',
      connectionActive: '#3fb950',
      connectionInactive: '#6e7681',
      modified: '#58a6ff',
      deleted: '#f85149',
      new: '#7ee787',
    },
  },
  typography: {
    fontFamily: {
      base: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif',
      mono: 'SFMono-Regular, Consolas, Liberation Mono, Menlo, monospace',
    },
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
    },
  },
  layout: {
    borderRadius: {
      sm: '0.25rem',
      base: '0.5rem',
      lg: '0.75rem',
      xl: '1rem',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      base: '1rem',
      lg: '1.5rem',
      xl: '2rem',
    },
  },
  monacoTheme: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '8B949E' },
      { token: 'keyword', foreground: 'FF7B72' },
      { token: 'string', foreground: 'A5D6FF' },
      { token: 'number', foreground: '79C0FF' },
      { token: 'regexp', foreground: 'A5D6FF' },
      { token: 'operator', foreground: 'FF7B72' },
      { token: 'namespace', foreground: 'FF7B72' },
      { token: 'type', foreground: 'FFA657' },
      { token: 'struct', foreground: 'FFA657' },
      { token: 'class', foreground: 'FFA657' },
      { token: 'interface', foreground: 'FFA657' },
      { token: 'enum', foreground: 'FFA657' },
      { token: 'typeParameter', foreground: 'FFA657' },
      { token: 'function', foreground: 'D2A8FF' },
      { token: 'member', foreground: 'D2A8FF' },
      { token: 'macro', foreground: 'D2A8FF' },
      { token: 'variable', foreground: 'C9D1D9' },
      { token: 'parameter', foreground: 'C9D1D9' },
      { token: 'property', foreground: 'C9D1D9' },
      { token: 'label', foreground: 'FF7B72' },
    ],
    colors: {
      'editor.background': '#0D1117',
      'editor.foreground': '#C9D1D9',
      'editorLineNumber.foreground': '#484F58',
      'editorLineNumber.activeForeground': '#C9D1D9',
      'editor.selectionBackground': '#264F78',
      'editor.selectionHighlightBackground': '#264F78',
      'editor.wordHighlightBackground': '#264F78',
      'editor.wordHighlightStrongBackground': '#264F78',
      'editor.findMatchBackground': '#2EA043',
      'editor.findMatchHighlightBackground': '#2EA043',
      'editor.findRangeHighlightBackground': '#264F78',
      'editor.hoverHighlightBackground': '#264F78',
      'editorCursor.foreground': '#58A6FF',
      'editorIndentGuide.background': '#21262D',
      'editorIndentGuide.activeBackground': '#30363D',
      'editorLineHighlightBackground': '#161B22',
      'editorLink.activeForeground': '#58A6FF',
    },
  },
};
