import type { Theme } from '../../types/theme';

export const highContrast: Theme = {
  id: 'high-contrast',
  name: 'High Contrast',
  isPreset: true,
  isReadOnly: true,
  colors: {
    bg: {
      base: '#000000',
      elevated: '#1a1a1a',
      overlay: '#2a2a2a',
      input: '#000000',
      tooltip: '#1a1a1a',
    },
    surface: {
      primary: '#1a1a1a',
      secondary: '#2a2a2a',
      tertiary: '#3a3a3a',
      hover: '#2a2a2a',
      active: '#ffffff',
      disabled: '#1a1a1a',
    },
    text: {
      primary: '#ffffff',
      secondary: '#e0e0e0',
      muted: '#a0a0a0',
      disabled: '#808080',
      accent: '#ffffff',
      inverse: '#000000',
    },
    accent: {
      primary: '#ffffff',
      secondary: '#ffff00',
      success: '#00ff00',
      warning: '#ffff00',
      error: '#ff0000',
      info: '#00ffff',
    },
    border: {
      subtle: '#1a1a1a',
      default: '#808080',
      strong: '#ffffff',
      focus: '#ffffff',
    },
    semantic: {
      string: '#ffff00',
      number: '#00ffff',
      boolean: '#ff00ff',
      date: '#00ff00',
      null: '#808080',
      primaryKey: '#ff8000',
      foreignKey: '#00ffff',
      index: '#ff00ff',
      connectionActive: '#00ff00',
      connectionInactive: '#808080',
      modified: '#ffffff',
      deleted: '#ff0000',
      new: '#00ff00',
    },
  },
  typography: {
    fontFamily: {
      base: 'Inter, system-ui, sans-serif',
      mono: 'Consolas, monospace',
    },
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
    },
  },
  layout: {
    borderRadius: {
      sm: '0',
      base: '0',
      lg: '0',
      xl: '0',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      base: '1rem',
      lg: '1.5rem',
      xl: '2rem',
    },
  },
  monacoTheme: {
    base: 'hc-black',
    inherit: true,
    rules: [
      { token: 'comment', foreground: 'FFFFFF' },
      { token: 'keyword', foreground: 'FFFF00' },
      { token: 'string', foreground: 'FFFF00' },
      { token: 'number', foreground: '00FFFF' },
      { token: 'regexp', foreground: 'FFFF00' },
      { token: 'operator', foreground: 'FFFFFF' },
      { token: 'namespace', foreground: 'FFFF00' },
      { token: 'type', foreground: 'FF8000' },
      { token: 'struct', foreground: 'FF8000' },
      { token: 'class', foreground: 'FF8000' },
      { token: 'interface', foreground: 'FF8000' },
      { token: 'enum', foreground: 'FF8000' },
      { token: 'typeParameter', foreground: 'FF8000' },
      { token: 'function', foreground: '00FFFF' },
      { token: 'member', foreground: '00FFFF' },
      { token: 'macro', foreground: '00FFFF' },
      { token: 'variable', foreground: 'FFFFFF' },
      { token: 'parameter', foreground: 'FF8000' },
      { token: 'property', foreground: 'FFFFFF' },
      { token: 'label', foreground: 'FFFF00' },
    ],
    colors: {
      'editor.background': '#000000',
      'editor.foreground': '#FFFFFF',
      'editorLineNumber.foreground': '#FFFFFF',
      'editorLineNumber.activeForeground': '#FFFFFF',
      'editor.selectionBackground': '#FFFFFF',
      'editor.selectionHighlightBackground': '#FFFFFF',
      'editor.wordHighlightBackground': '#FFFFFF',
      'editor.wordHighlightStrongBackground': '#FFFFFF',
      'editor.findMatchBackground': '#FFFF00',
      'editor.findMatchHighlightBackground': '#FFFF00',
      'editor.findRangeHighlightBackground': '#FFFFFF',
      'editor.hoverHighlightBackground': '#FFFFFF',
      'editorCursor.foreground': '#FFFFFF',
      'editorIndentGuide.background': '#FFFFFF',
      'editorIndentGuide.activeBackground': '#FFFFFF',
      'editorLineHighlightBackground': '#1A1A1A',
      'editorLink.activeForeground': '#00FFFF',
    },
  },
};
