import type { Theme } from '../../types/theme';

export const monokai: Theme = {
  id: 'monokai',
  name: 'Monokai',
  author: 'Wimer Hazenberg',
  isPreset: true,
  isReadOnly: true,
  colors: {
    bg: {
      base: '#272822',
      elevated: '#1e1f1c',
      overlay: '#3e3d32',
      input: '#272822',
      tooltip: '#3e3d32',
    },
    surface: {
      primary: '#3e3d32',
      secondary: '#49483e',
      tertiary: '#575654',
      hover: '#49483e',
      active: '#66d9ef',
      disabled: '#3e3d32',
    },
    text: {
      primary: '#f8f8f2',
      secondary: '#a59f85',
      muted: '#75715e',
      disabled: '#49483e',
      accent: '#66d9ef',
      inverse: '#272822',
    },
    accent: {
      primary: '#66d9ef',
      secondary: '#ae81ff',
      success: '#a6e22e',
      warning: '#e6db74',
      error: '#f92672',
      info: '#66d9ef',
    },
    border: {
      subtle: '#3e3d32',
      default: '#49483e',
      strong: '#575654',
      focus: '#66d9ef',
    },
    semantic: {
      string: '#e6db74',
      number: '#ae81ff',
      boolean: '#ae81ff',
      date: '#a6e22e',
      null: '#75715e',
      primaryKey: '#fd971f',
      foreignKey: '#66d9ef',
      index: '#ae81ff',
      connectionActive: '#a6e22e',
      connectionInactive: '#75715e',
      modified: '#66d9ef',
      deleted: '#f92672',
      new: '#a6e22e',
    },
  },
  typography: {
    fontFamily: {
      base: 'Inter, system-ui, sans-serif',
      mono: 'Monaco, Consolas, monospace',
    },
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
    },
  },
  layout: {
    borderRadius: {
      sm: '0.25rem',
      base: '0.5rem',
      lg: '0.75rem',
      xl: '1rem',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      base: '1rem',
      lg: '1.5rem',
      xl: '2rem',
    },
  },
  monacoTheme: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '75715E' },
      { token: 'keyword', foreground: 'F92672' },
      { token: 'string', foreground: 'E6DB74' },
      { token: 'number', foreground: 'AE81FF' },
      { token: 'regexp', foreground: 'E6DB74' },
      { token: 'operator', foreground: 'F92672' },
      { token: 'namespace', foreground: 'F92672' },
      { token: 'type', foreground: '66D9EF' },
      { token: 'struct', foreground: '66D9EF' },
      { token: 'class', foreground: '66D9EF' },
      { token: 'interface', foreground: '66D9EF' },
      { token: 'enum', foreground: '66D9EF' },
      { token: 'typeParameter', foreground: '66D9EF' },
      { token: 'function', foreground: 'A6E22E' },
      { token: 'member', foreground: 'A6E22E' },
      { token: 'macro', foreground: 'A6E22E' },
      { token: 'variable', foreground: 'F8F8F2' },
      { token: 'parameter', foreground: 'FD971F' },
      { token: 'property', foreground: 'F8F8F2' },
      { token: 'label', foreground: 'F92672' },
    ],
    colors: {
      'editor.background': '#272822',
      'editor.foreground': '#F8F8F2',
      'editorLineNumber.foreground': '#90908A',
      'editorLineNumber.activeForeground': '#C2C2BF',
      'editor.selectionBackground': '#49483E',
      'editor.selectionHighlightBackground': '#3E3D32',
      'editor.wordHighlightBackground': '#49483E',
      'editor.wordHighlightStrongBackground': '#49483E',
      'editor.findMatchBackground': '#FFE792',
      'editor.findMatchHighlightBackground': '#FFE792',
      'editor.findRangeHighlightBackground': '#3E3D32',
      'editor.hoverHighlightBackground': '#49483E',
      'editorCursor.foreground': '#F8F8F2',
      'editorIndentGuide.background': '#3E3D32',
      'editorIndentGuide.activeBackground': '#49483E',
      'editorLineHighlightBackground': '#3E3D32',
      'editorLink.activeForeground': '#66D9EF',
    },
  },
};
