import type { Theme } from '../../types/theme';

export const oneDarkPro: Theme = {
  id: 'one-dark-pro',
  name: 'One Dark Pro',
  author: 'BinaryFy',
  isPreset: true,
  isReadOnly: true,
  colors: {
    bg: {
      base: '#282c34',
      elevated: '#21252b',
      overlay: '#2c313a',
      input: '#1e2227',
      tooltip: '#21252b',
    },
    surface: {
      primary: '#21252b',
      secondary: '#2c313a',
      tertiary: '#373d48',
      hover: '#2c313a',
      active: '#3e4451',
      disabled: '#21252b',
    },
    text: {
      primary: '#abb2bf',
      secondary: '#828997',
      muted: '#5c6370',
      disabled: '#4b5263',
      accent: '#61afef',
      inverse: '#282c34',
    },
    accent: {
      primary: '#61afef',
      secondary: '#c678dd',
      success: '#98c379',
      warning: '#e5c07b',
      error: '#e06c75',
      info: '#56b6c2',
    },
    border: {
      subtle: '#21252b',
      default: '#3e4451',
      strong: '#5c6370',
      focus: '#61afef',
    },
    semantic: {
      string: '#e06c75',
      number: '#d19a66',
      boolean: '#c678dd',
      date: '#98c379',
      null: '#5c6370',
      primaryKey: '#e5c07b',
      foreignKey: '#56b6c2',
      index: '#c678dd',
      connectionActive: '#98c379',
      connectionInactive: '#5c6370',
      modified: '#61afef',
      deleted: '#e06c75',
      new: '#98c379',
    },
  },
  typography: {
    fontFamily: {
      base: 'Inter, system-ui, sans-serif',
      mono: 'Fira Code, Monaco, Consolas, monospace',
    },
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
    },
  },
  layout: {
    borderRadius: {
      sm: '0.25rem',
      base: '0.5rem',
      lg: '0.75rem',
      xl: '1rem',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      base: '1rem',
      lg: '1.5rem',
      xl: '2rem',
    },
  },
  monacoTheme: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '5C6370', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'C678DD' },
      { token: 'string', foreground: '98C379' },
      { token: 'number', foreground: 'D19A66' },
      { token: 'regexp', foreground: '98C379' },
      { token: 'operator', foreground: '56B6C2' },
      { token: 'namespace', foreground: 'E06C75' },
      { token: 'type', foreground: 'E5C07B' },
      { token: 'struct', foreground: 'E5C07B' },
      { token: 'class', foreground: 'E5C07B' },
      { token: 'interface', foreground: 'E5C07B' },
      { token: 'enum', foreground: 'E5C07B' },
      { token: 'typeParameter', foreground: 'E5C07B' },
      { token: 'function', foreground: '61AFEF' },
      { token: 'member', foreground: '61AFEF' },
      { token: 'macro', foreground: '61AFEF' },
      { token: 'variable', foreground: 'E06C75' },
      { token: 'parameter', foreground: 'ABB2BF' },
      { token: 'property', foreground: 'E06C75' },
      { token: 'label', foreground: 'C678DD' },
    ],
    colors: {
      'editor.background': '#282C34',
      'editor.foreground': '#ABB2BF',
      'editorLineNumber.foreground': '#4B5263',
      'editorLineNumber.activeForeground': '#ABB2BF',
      'editor.selectionBackground': '#3E4451',
      'editor.selectionHighlightBackground': '#3E4451',
      'editor.wordHighlightBackground': '#3E4451',
      'editor.wordHighlightStrongBackground': '#3E4451',
      'editor.findMatchBackground': '#5C6370',
      'editor.findMatchHighlightBackground': '#5C6370',
      'editor.findRangeHighlightBackground': '#3E4451',
      'editor.hoverHighlightBackground': '#3E4451',
      'editorCursor.foreground': '#528BFF',
      'editorIndentGuide.background': '#3B4048',
      'editorIndentGuide.activeBackground': '#5C6370',
      'editorLineHighlightBackground': '#2C313A',
      'editorLink.activeForeground': '#61AFEF',
    },
  },
};
