import type { Theme } from '../../types/theme';

export const tabularisDark: Theme = {
  id: 'tabularis-dark',
  name: 'Tabularis Dark',
  isPreset: true,
  isReadOnly: true,
  colors: {
    bg: {
      base: '#020617',
      elevated: '#0f172a',
      overlay: '#1e293b',
      input: '#0f172a',
      tooltip: '#1e293b',
    },
    surface: {
      primary: '#1e293b',
      secondary: '#334155',
      tertiary: '#475569',
      hover: '#334155',
      active: '#3b82f6',
      disabled: '#1e293b',
    },
    text: {
      primary: '#f8fafc',
      secondary: '#94a3b8',
      muted: '#64748b',
      disabled: '#475569',
      accent: '#3b82f6',
      inverse: '#020617',
    },
    accent: {
      primary: '#3b82f6',
      secondary: '#8b5cf6',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#06b6d4',
    },
    border: {
      subtle: '#1e293b',
      default: '#334155',
      strong: '#475569',
      focus: '#3b82f6',
    },
    semantic: {
      string: '#f87171',
      number: '#60a5fa',
      boolean: '#a78bfa',
      date: '#4ade80',
      null: '#64748b',
      primaryKey: '#fbbf24',
      foreignKey: '#22d3ee',
      index: '#c084fc',
      connectionActive: '#22c55e',
      connectionInactive: '#64748b',
      modified: '#3b82f6',
      deleted: '#ef4444',
      new: '#22c55e',
    },
  },
  typography: {
    fontFamily: {
      base: 'Inter, system-ui, Avenir, Helvetica, Arial, sans-serif',
      mono: 'JetBrains Mono, Fira Code, Monaco, Consolas, monospace',
    },
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
    },
  },
  layout: {
    borderRadius: {
      sm: '0.25rem',
      base: '0.5rem',
      lg: '0.75rem',
      xl: '1rem',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      base: '1rem',
      lg: '1.5rem',
      xl: '2rem',
    },
  },
  monacoTheme: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '64748B', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'C084FC' },
      { token: 'string', foreground: 'F87171' },
      { token: 'number', foreground: '60A5FA' },
      { token: 'regexp', foreground: 'F87171' },
      { token: 'operator', foreground: '94A3B8' },
      { token: 'namespace', foreground: 'F87171' },
      { token: 'type', foreground: 'FBBF24' },
      { token: 'struct', foreground: 'FBBF24' },
      { token: 'class', foreground: 'FBBF24' },
      { token: 'interface', foreground: 'FBBF24' },
      { token: 'enum', foreground: 'FBBF24' },
      { token: 'typeParameter', foreground: 'FBBF24' },
      { token: 'function', foreground: '60A5FA' },
      { token: 'member', foreground: '60A5FA' },
      { token: 'macro', foreground: '60A5FA' },
      { token: 'variable', foreground: 'F87171' },
      { token: 'parameter', foreground: '94A3B8' },
      { token: 'property', foreground: 'F87171' },
      { token: 'label', foreground: 'C084FC' },
    ],
    colors: {
      'editor.background': '#020617',
      'editor.foreground': '#F8FAFC',
      'editorLineNumber.foreground': '#475569',
      'editorLineNumber.activeForeground': '#94A3B8',
      'editor.selectionBackground': '#334155',
      'editor.selectionHighlightBackground': '#1E293B',
      'editor.wordHighlightBackground': '#334155',
      'editor.wordHighlightStrongBackground': '#334155',
      'editor.findMatchBackground': '#3B82F6',
      'editor.findMatchHighlightBackground': '#1D4ED8',
      'editor.findRangeHighlightBackground': '#1E293B',
      'editor.hoverHighlightBackground': '#334155',
      'editorCursor.foreground': '#3B82F6',
      'editorIndentGuide.background': '#1E293B',
      'editorIndentGuide.activeBackground': '#334155',
      'editorLineHighlightBackground': '#0F172A',
      'editorLink.activeForeground': '#3B82F6',
      'editorBracketMatch.background': '#334155',
      'editorBracketMatch.border': '#3B82F6',
    },
  },
};
