/**
 * External links used throughout the application.
 *
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated by scripts/sync-links.js
 * To update links, modify the "links" section in package.json and run: pnpm sync-links
 */

export const LINKS = {
  DISCORD: "https://discord.gg/YrZPHAwMSG",
  GITHUB: "https://github.com/debba/tabularis",
} as const;

// Named exports for convenience
export const DISCORD_URL = LINKS.DISCORD;
export const GITHUB_URL = LINKS.GITHUB;
