import { readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';

// File paths
const paths = {
  package: resolve('package.json'),
  configLinks: resolve('src/config/links.ts'),
  readme: resolve('README.md'),
  contributing: resolve('CONTRIBUTING.md'),
  website: resolve('website/index.html')
};

// 1. Read links from package.json
const pkg = JSON.parse(readFileSync(paths.package, 'utf-8'));
const links = pkg.links;

if (!links) {
  console.error('❌ No "links" section found in package.json');
  process.exit(1);
}

console.log('🔄 Syncing links...');
console.log(`   Discord: ${links.discord}`);
console.log(`   GitHub: ${links.github}`);

// 2. Create/update src/config/links.ts
const linksConfig = `/**
 * External links used throughout the application.
 *
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated by scripts/sync-links.js
 * To update links, modify the "links" section in package.json and run: pnpm sync-links
 */

export const LINKS = {
  DISCORD: "${links.discord}",
  GITHUB: "${links.github}",
} as const;

// Named exports for convenience
export const DISCORD_URL = LINKS.DISCORD;
export const GITHUB_URL = LINKS.GITHUB;
`;

writeFileSync(paths.configLinks, linksConfig);
console.log('✅ Updated src/config/links.ts');

// 3. Update README.md - Discord links
let readme = readFileSync(paths.readme, 'utf-8');
readme = readme.replace(
  /https:\/\/discord\.gg\/[A-Za-z0-9]+/g,
  links.discord
);
writeFileSync(paths.readme, readme);
console.log('✅ Updated README.md');

// 4. Update CONTRIBUTING.md - Discord links
let contributing = readFileSync(paths.contributing, 'utf-8');
contributing = contributing.replace(
  /https:\/\/discord\.gg\/[A-Za-z0-9]+/g,
  links.discord
);
writeFileSync(paths.contributing, contributing);
console.log('✅ Updated CONTRIBUTING.md');

// 5. Update website/index.html - Discord links
let website = readFileSync(paths.website, 'utf-8');
website = website.replace(
  /https:\/\/discord\.gg\/[A-Za-z0-9]+/g,
  links.discord
);
writeFileSync(paths.website, website);
console.log('✅ Updated website/index.html');

console.log('\n✨ All links synced successfully!');
console.log('\n💡 React components automatically use the updated links from src/config/links.ts');
